# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73d5e4db83f157bc6855519a88a9573d04d1dcf4fc0529f4b7d8b020e6df9985b2e2a0e3ffae5f216153678b2615135c505dc36cdbb9443591b0c82c870b331e

test:
  secret_key_base: 76376ec86b40c2f0ae8a96a2cadc00a8c1ef4ca3e549b67ac2ebbf25cf4b1e445d19cf3ae2c1b4fd6d0b509723238cac6afa52379cfbaddd5ee8ca765e1d5160

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
